# Project information
site_name: Jespers second brain
site_url: https://sitename.example
site_author: Jesper van Beemdelust
site_description: >-
  This website will contain a collection of knowledge articles, how-to's (SOPs) and other useful information that I want to keep track of.

# Repository
repo_name: jespervb7/jespers-second-brain
repo_url: https://github.com/jespervb7/jespers-second-brain

theme:
  features:
    - navigation.footer
    - navigation.top
    - navigation.path
    - navigation.tabs 
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

  name: material
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - toc:
        title: On this page
        permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search
  - tags:
      PowerBI: PBI

extra:
  social:
    - icon: simple/docusaurus
      link: https://youtube.com/@james-willett
    - icon: simple/docusaurus
      link: https://linkedin.com/in/willettjames

nav:
  - Home: index.md
  - Guides:
    - guides/guides.md
    - guides/creating aliases for git.md
  - SOPs:
    - sops/sops.md
    - sops/fresh pc installation.md
  - Knowledge articles: knowledge/knowledge.md
  - Snippets:
    - snippets/snippets.md
    - Power BI: snippets/Power BI.md
    - TMDL scripts:
      - snippets/tmdl/template semantic model.md
      - snippets/tmdl/dim date.md
    - Prompts:
      - snippets/prompts/calculate-visual-sizes.md
      - snippets/prompts/table-column descriptions.md
    - Templates:
      - snippets/templates/SOPs.md
    

  - Ideas: ideas/ideas.md
  - Errors: errors/errors.md
  - Workflows: workflows/workflows.md
  - Blog: blog/blog.md
  - Tags: tags.md
  - test:
    - useful mkdocs things.md
    - Section:
      - test.md
      - test page: test2.md
    - Section 2: test1.md
    - Section 3:
      - test3.md
  - About: about.md